config/routes.rb
TestApp::Application.routes.draw do

    resources :users, :controller => 'agency/users' do
      member do
        post :toggle_admin_role
      end
    end

    resources :trips, :only => [:index, :new,:create,:show, :edit, :update], :controller => 'agency/trips'

    resource :profile, :only => [:edit, :update], :controller => 'agency/profiles' do
      resources :logos, :only => [:create, :show], :controller => 'agency/logos'
    end

  root :to => redirect("/profile/edit")
  

end

app/models/agency.rb
class Agency < ActiveRecord::Base
  attr_accessible :address, :city, :name, :phone, :state_id, :url, :zip_code, :subdomain, :owner_attributes
  
  has_many :users
  has_many :logos
  has_many :trips
  belongs_to :state

  belongs_to :owner, :class_name => 'User', :foreign_key => 'owner_id'
  accepts_nested_attributes_for :owner

  has_many :admins, :class_name => 'User', :conditions => {:role_id => Role.agency_admin.try(:id)}
  has_many :users
  has_many :pictures, :as => :imageable
  # just because trip has_many :addons, doesn't mean we can automagically
  # use the following association (has_many :through needs join models)
  # has_many :addons, :through => :trips

  before_create :capitalize_name

  validates_presence_of :name


  # if Rails.env.test?
  #   # This is just an awful workaround since capybara is not loading has_one association properly
  #   def admin
  #     users.find_by_role_id(Role.agency_admin.try(:id))
  #   end
  # end
  # 
  def profile_complete?
    self.subdomain.present? && self.name.present? && self.owner.profile_complete?
  end

  private

  def capitalize_name
    self.name.capitalize! unless self.name.blank?
  end

end

app/models/logo.rb
class Logo < ActiveRecord::Base
  attr_accessible :agency_id, :current

  attr_accessor :image_width, :image_height

  belongs_to :agency

  mount_uploader :image, ImageUploader
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :image, :imageable_id, :imageable_type
  belongs_to :imageable, :polymorphic => true
  mount_uploader :image, ImageableUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :description, :name

  has_many :users

  class << self
    ["Agency Admin", "Agency User", "Account Owner", "Participant"].each do |role_name|
      define_method role_name.downcase.gsub(/ /, "_") do
        find_by_name(role_name)
      end
    end
  end
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :abbr, :name
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  attr_accessible :name, :destination, :group_name 

  belongs_to :agency
  has_many :pictures, :as => :imageable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Setup accessible (or protected) attributes for your model
  attr_accessible :id, :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :phone, :title, :gender, :office_phone, :agency_attributes, :authentication_tokens, :trip_users, :trips_manageds
  # attr_accessible :title, :body
  attr_accessible :agency_id, :role_id
  has_many :pictures, :as => :imageable  

  belongs_to :agency

  belongs_to :role

  validates_presence_of :first_name, :on => :update
  validates_presence_of :last_name, :on => :update
  validates_presence_of :email

  after_create :send_invitation
  
  def full_name
    [first_name, last_name].compact.join(' ').titleize.string_or_nil || email
  end

  def send_invitation
    if !self.role.blank?
      EmailSender.invitation_email(self).deliver if self.role.id==Role.agency_user.id
    end
  end

  def owns?(agency)
    if agency.is_a? Agency
      return agency.owner_id == self.id
    end
    false
  end

  def profile_complete?
    self.first_name.present? && self.last_name.present?
  end

  def admin?
    self.role_id == Role.agency_admin.id
  end

  def is_active?
    return self.sign_in_count > 0
  end

  def full_title
    return self.title.capitalize unless self.title.blank?
  end

end

app/controllers/agency/base_controller.rb
class Agency::BaseController < ApplicationController
end

app/controllers/agency/logos_controller.rb
class Agency::LogosController < Agency::BaseController
  def create
    @agency = Agency.find(@current_agency.id)
    @logo = @agency.logos.build
    @logo.image = params[:photo][:image]
    if @logo.save
      render :json => {
        :success => true,
        :url => @logo.image.url,
        :thumb_url => @logo.image.thumb.url,
        :w => @logo.image_width,
        :h => @logo.image_height
      }.to_json
    else
      render :text => "{'success': false, 'errors': []}", :content_type => "application/json"
    end
  end
end

app/controllers/agency/profiles_controller.rb
class Agency::ProfilesController < Agency::BaseController
  layout "agency"

  def edit
    @agency = Agency.find(@current_agency.id)
  end

  def update
    @agency = Agency.find(@current_agency.id)
    if @agency.update_attributes(params[:agency])
      if !@agency.subdomain.eql?(@current_agency.subdomain)
        redirect_to new_user_session_url(:subdomain => @agency.subdomain, :auth_token => current_user.authentication_token)
      else
        redirect_to root_url(:subdomain => @agency.subdomain)
      end
    else
      render :edit
    end
  end
end

app/controllers/agency/trips_controller.rb
class Agency::TripsController < Agency::BaseController
  layout 'agency'


  def update
    @trip = current_agency.trips.find(params[:id])
    done = @trip.update_attributes(params[:trip])   
    validate_done(done)
  end

  def edit
    @trip = Trip.find(params[:id])
    render 'new'
  end

  def show
    @trip = Trip.
      includes(:users, :agency, :packages, :addons, :payments, :deadlines).
      find(params[:id])
  end
end

app/controllers/agency/users_controller.rb
class Agency::UsersController < Agency::BaseController
  layout 'agency'

  def edit
    @user = find_user
  end

  def update
    @user = find_user
    if @user.update_attributes(params[:user]) 
      flash[:success] = "your profile has been saved"
      redirect_to "/"
    end
  end

  private

  def find_user
    User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include UrlHelper

  before_filter :current_agency
  

  protected

  def current_user
    @current_user ||= User.find(1)
  end

  helper_method :current_user

  def current_agency
    @current_agency ||= Agency.find(1)
  end

  helper_method :current_agency

  def not_found
    raise ActionController::RoutingError.new('404')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { " - #{page_title.to_s}".html_safe }
  end
  
  def link_to_remove_fields(image_name,style_class, f)
    f.hidden_field(:_destroy) + link_to_function(image_tag("icn/"+image_name, :border => 0), "remove_fields(this)", :class => style_class)
  end
end

app/helpers/url_helper.rb
module UrlHelper
  def with_subdomain(subdomain)
    subdomain = (subdomain || "")
    subdomain += "." unless subdomain.empty?
    [subdomain, request.domain(SUBDOMAIN_SIZE)].join
    #[subdomain, request.domain, request.port_string].join
  end

  def url_for(options = nil)
    if options.kind_of?(Hash) && options.has_key?(:subdomain)
      options[:host] = with_subdomain(options.delete(:subdomain))
    end
    super
  end
end

app/views/agency/profiles/_owner_info.html.haml
.cont
  = render :partial => 'shared/errors', :locals => {:model => owner}
  %h3.title Your Info
  .clear.form
    = f.simple_fields_for :owner do |uf|
      %p.inline.input.w280{:class => "#{owner.errors.include?(:first_name) ? "error" : ""}"}
        %span.bginput
          %span.icn.usersm
        = uf.text_field :first_name, :class => "text", :"data-placeholder" => "First Name"
      %p.inline.input.w280.nmr{:class => "#{owner.errors.include?(:last_name) ? "error" : ""}"}
        %span.bginput
          %span.icn.usersm
        = uf.text_field :last_name, :class => "text", :"data-placeholder" => "Last Name"
      %p.inline.input.w280
        %span.bginput
          %span.icn.phone
        = uf.text_field :phone, :class => "text", :"data-placeholder" => "Phone Number"
      %p.inline.input.w280.nmr
        %span.bginput
          %span.icn.title
        = uf.text_field :title, :class => "text", :"data-placeholder" => "Title"

app/views/agency/profiles/edit.html.haml
.cont_right
  = form_for(@agency, :url => profile_path, :html => { :method => :put }) do |f|
    .cont
      = render :partial => 'shared/filtered_errors', :locals => {:model => @agency}
      %h3.title Agency Profile
      %h3 Change agency logo
      .left.w325
        .browse.big
          .contbrow
            .modalwin
              %span.add
              .modal.w680
                %h2 Select agency logo
                %section
                  .left.w317
                    .crop_container
                      = image_tag("misc/picture_select.png", class: 'target js-jcrop')
                  .photos
                    %ul
                      - @agency.pictures.each do |logo|
                        - dimensions = logo.image.capture_size_after_retrieve_from_cache("").map(&:to_i)
                        %li
                          %a{:href => "#", :"data-url" => logo.image.url, :"data-width" => dimensions[0], :"data-height" => dimensions[1]}
                            = image_tag(logo.image.thumb.url)
                %section
                  #file-uploader.left
                    %noscript
                      %p Please enable JavaScript to use file uploader.
                  %ul.buttons
                    %li
                      %a.x.linkunderline{:href => "#"} Cancel
                    %li.or Or
                    %li
                      %a.button.green2{:href => "#"} Save
            %ul.foobrowse
              %li.first
                %a{:href => "#"}
              %li.last
                %a{:href => "#"}
                  %span
        %p.inputfooter Prefered dimensions 300px x 100px

    .cont.notbor
      %ul.buttons
        %li
          %a.linkunderline{:href => root_url} Cancel
        %li.or Or
        %li
          = f.submit "Finish", :class => "button green2"

app/views/agency/shared/_flash_error.html.haml
- flash.each do|key,value|
  %span{:class => "#{key ==:error ? "db_error" : "db_ok"}"}
    %span.title
      = "#{key ==:error ? "Oops!" : "Congratulations!"}"
      %a{:style => "cursor:pointer;", :onclick => "$('.db_error').remove();$('.db_ok').remove();"}
        = image_tag("icn/icn_close.png",:alt => "Close")
    %span.info
      =  value
    %span.hint-pointer

app/views/agency/shared/_footer.html.haml
%footer
  %ul.right
/ FOOTER END

app/views/agency/shared/_general_error.html.haml
- if !resource.errors.empty?
  %span.db_error
    %span.title
      = "Oops!"
      %a{:style => "cursor:pointer;", :onclick => "$('.db_error').remove();"}
        = image_tag("icn/icn_close.png",:alt => "Close")
    - resource.errors.each do |head, msg|
      %span.info
        = msg
    %span.hint-pointer

app/views/agency/shared/_header.html.haml
%header
  %h2.logo= link_to @current_agency.name, "/"
  .rightheader
    %ul
      %li
        = link_to "Trip settings", edit_trip_path(id: 1)
      %li
        = link_to "Agency settings", edit_profile_path
      %li
        %a{:href => "#"} Help & Support
    #dropdown
      %a.dropdown{:href => "#dropdown"}
        = image_tag("misc/profile.png", :class => "img")
        = current_user.full_name
        %span.icn_drop
      .options
        = link_to "Edit Profile", edit_user_path(current_user)
        = link_to "Log Out", "#"
/ HEADER END

app/views/agency/shared/_header_basic.html.haml
%header
  %h2.logo= link_to @current_agency.name, "/"
  .rightheader
    %ul
      %li
        %a{:href => "#"} Help & Support
    #dropdown
      %a.dropdown{:href => "#dropdown"}
        = image_tag("misc/profile.png", :class => "img")
        = current_user.full_name
        %span.icn_drop
      .options
        = link_to "Edit Profile", edit_user_path(current_user)
        = link_to "Log Out", '#'
/ HEADER END

app/views/agency/shared/_menu.html.haml
%aside.menugeneral

app/views/agency/shared/_menu_basic.html.haml
%aside.menugeneral

app/views/agency/shared/_scripts.html.haml
/
  JS
  \==================================================
= javascript_include_tag "application"
= yield(:javascript)
/[if lt IE 9]
  <script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"></script>

app/views/agency/shared/_topbar.html.haml
.menu
  %ul
    %li.first
      = render :partial => 'agency/shared/notifications'
    %li.search
      %form#search_form{:action => "", :method => "get"}
        %input.bg_search{:onblur => "if (this.value == '') {this.value = 'Search';}", :onfocus => "if (this.value == 'Search') {this.value = '';}", :type => "text", :value => "Search"}/

app/views/agency/trips/_basic_step.html.haml
= form_for([@trip]) do |f|
  = hidden_field_tag :step, @current_step

  .cont_right
    .cont
      = render 'title', trip: @trip
      .step
        %ul
          %li
            = image_tag("icn/icn_steps.png")
          %li.active
            Step 1
            %span

            %li= "Step2"
            %li= "Step3"
            %li= "Step4"
            %li= "Step5"

      = render :partial => 'agency/shared/general_error', :locals => {:resource => @trip}
      %h3 Basic Information
      .left
        .browse.big2
          .contbrow
            .modalwin
              %span.add
              %span.big Add trip picture
              .modal.w680
                %h2 Select Trip Picture
                %section
                  .left.w317
                    .crop_container
                      = image_tag("misc/picture_select.png", class: 'target js-jcrop')
                  .photos
                    %ul
                      %li
                        %a{:href => "#"}
                          = image_tag("misc/picture.png")
                      %li
                        %a{:href => "#"}
                          = image_tag("misc/picture.png")
                      %li
                        %a{:href => "#"}
                          = image_tag("misc/picture.png")
                %section
                  %span.left.filegray
                    %input.file{:style => "opacity: 0;", :type => "file"}/
                  %ul.buttons
                    %li
                      %a.x.linkunderline{:href => "#"} Cancel
                    %li.or Or
                    %li
                      %a.button.green2{:href => "#"} Save
            %ul.foobrowse
              %li.first
                %a{:href => "#"}
              %li.last
                %a{:href => "#"}
                  %span
      .form.ageprof
        %p.input.w280
          %span.bginput
            %span.icn.trip
          = f.text_field :name, :class=>"text", 'data-placeholder' => "Trip Name *"
        %p.input.w280
          %span.bginput
            %span.icn.destination
          = f.text_field :destination, :class=>"text", 'data-placeholder' => "Destination *"
        %p.input.w280
          %span.bginput
            %span.icn.group
          = f.text_field :group_name, :class=>"text", 'data-placeholder' => "Group Name *"
      .clear
      
      %ul.buttons
        %li
          %a.button.disabled{} Back
        %li
          = f.submit "Next", :class => "button green2"

app/views/agency/trips/_title.html.haml
- if trip.new_record?
  %h3.title New Trip
- else
  %h3.title
    = link_to trip.name, trip_path(trip)

app/views/agency/trips/new.html.haml
= render "basic_step"

app/views/agency/users/_user_error.html.haml
- if !user.errors.empty?
  %span.db_error
    %span.title
      Oops!, one error had ocurred
      %a{:href => "#"}
        = image_tag("icn/icn_close.png")
    - user.errors.full_messages.each do |msg|
      %span.info 
        = "#{msg}"
      %span.hint-pointer

app/views/agency/users/edit.html.haml
.cont_right
  .cont
    %h3.title Edit User
    = render :partial => "user_error", :locals => {:user => @user}
    .browse.small
      .contbrow
        .modalwin
          %span.add
          %span Add User Picture
          .modal.w680
            %h2 Add User Picture
            %section
              .left.w317
                .crop_container
                  = image_tag("misc/picture_select.png", class: 'target js-jcrop')
              .photos
                %ul
                  %li
                    %a{:href => "#"}
                      = image_tag "misc/picture.png"
                  %li
                    %a{:href => "#"}
                      = image_tag "misc/picture.png"
            %section
              %span.left.filegray
                %input.file{:style => "opacity: 0;", :type => "file"}/
              %ul.buttons
                %li
                  %a.x.linkunderline{:href => "#"} Cancel
                %li.or Or
                %li
                  %a.button.green2{:href => "#"} Save
        %ul.foobrowse
          %li.first
            %a{:href => "#"}
          %li.last
            %a{:href => "#"}
              %span
    = form_for([@user]) do |f|
      .form.dash
        %p.inputsmall
          = f.select :gender,  [['Mr', 'M'], ['Mrs', 'F']]
        %p.input.w376
          %span.bginput
            %span.icn.usersm
          = f.text_field :first_name, :class=>"text", 'data-placeholder' => "First Name"
        %p.input.w376
          %span.bginput
            %span.icn.usersm
          = f.text_field :last_name, :class=>"text", 'data-placeholder' => "Last Name"
        %p.input.w376
          %span.bginput
            %span.icn.title
          = f.text_field :title, :class=>"text", 'data-placeholder' => "Title"
        %p.input.w376
          %span.bginput
            %span.icn.emailsm
          = f.text_field :email, :class=>"text", 'data-placeholder' => "Email"
        %p.input.w376
          %span.bginput
            %span.icn.perphonesm
          = f.text_field :phone, :class=>"text", 'data-placeholder' => "Personal Phone"
        %p.input.w376
          %span.bginput
            %span.icn.offphonesm
          = f.text_field :office_phone, :class=>"text", 'data-placeholder' => "Office Phone"
      .cont.notbor
        %ul.buttons
          %li
            = link_to "Cancel", :back, :class => "linkunderline"
          %li.or Or
          %li
            = f.submit "Save", :class => "button green2"

app/views/layouts/agency.html.haml
!!!
%html{:lang => "en-US"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Application
    = stylesheet_link_tag "application"
    = csrf_meta_tags
  %body
    .wrapper
      - if current_user.admin?
        = render :partial => 'agency/shared/header'
      - else
        = render :partial => 'agency/shared/header_basic'    
      = render :partial => 'agency/shared/topbar'
      #content
        - if current_user.admin?
          = render :partial => 'agency/shared/menu'
        - else
          = render :partial => 'agency/shared/menu_basic'
        = yield
      = render :partial => 'agency/shared/footer'
      = render :partial => 'agency/shared/scripts'

app/views/shared/_errors.html.haml
- unless model.errors.empty?
  %span.db_error
    %span.title
      Oops!
      = link_to image_tag("icn/icn_close.png", :alt => "Close"), "#"
    %span.info
      = "There were errors during this operation:"
      - model.errors.full_messages.each do |error_message|
        %p="- #{error_message}"
    %span.hint-pointer

app/views/shared/_filtered_errors.html.haml
- unless model.errors.empty?
  %span.db_error
    %span.title
      Oops!
      = link_to image_tag("icn/icn_close.png", :alt => "Close"), "#"
    %span.info
      = "There were errors during this operation:"
      - model.errors.each do |attrb, message|
        - next if attrb.to_s.index('.') 
        %p="- #{attrb.to_s.humanize} #{message}"
    %span.hint-pointer